---
version: '3.3'
services:
  database:
    image: mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: final
      MARIADB_USER: final
      MARIADB_PASSWORD: final

  web:
    depends_on:
      - database
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8880:80"
